version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: venky_admin
      MONGO_INITDB_ROOT_PASSWORD: venky_123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: venky_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: venky_123
      ME_CONFIG_MONGODB_URL: mongodb://venky_admin:venky_123@mongo:27017/
    depends_on:
      - mongo
